name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Cache Cargo
      uses: actions/cache@v2
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
        
    - name: Install OS deps
      run: |
        sudo apt-get install g++ pkg-config libx11-dev libasound2-dev libudev-dev

    - name: Build
      run: cargo build --verbose
    
    - name: Run tests
      run: cargo test --verbose
      
    - name: Run clippy
      run: cargo clippy --verbose
      
